# Generated by Django 3.2.8 on 2021-10-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='last_change_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='last_change_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
