# Generated by Django 3.2.8 on 2021-10-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211019_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='last_change_1',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='last_change_2',
        ),
    ]
